### ISSUE TITLE
I can't access to my own repository

### ISSUE THREAD

**Issue by ghost** [amchess/shashchessanalyzer#2]
Hi Andrea, Due to deleting my account, I have no access to my organization and no permission to commit. 
https://github.com/stockfish-nnue
@amchess, Could you please send me an invitation to join?
https://github.com/orgs/stockfish-nnue/people
Thank you!

**Comment by ghost** [comment]
@amchess, Are you here?

**Comment by KasparovChess** [comment]
@amchess, I also can't access to org repository. Please change my role to **owner**.

**Comment by KasparovChess** [comment]
@amchess, If you want to set someone as an admin for the entire organization:

1. Navigate to the Organization > People
<img src="https://i.sstatic.net/hMdM5.png" alt="org > people">

2. Identify the member you want to update and click on the settings cog
<img src="https://i.sstatic.net/GTGra.png" alt="settings > change role">

3. Set role to `Owner`
<img src="https://i.sstatic.net/xYZHq.png" alt="Select Role">
